# Generated by Django 5.1.7 on 2025-05-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cart_cartitem_order_orderitem_payment_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdesign',
            name='decoration_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customerdesign',
            name='material',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customerdesign',
            name='model_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdesign',
            name='generated_model',
            field=models.URLField(blank=True, null=True),
        ),
    ]
