# Generated by Django 5.1.7 on 2025-05-05 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_customerdesign_decoration_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdesign',
            old_name='design_prompt',
            new_name='design_description',
        ),
        migrations.RenameField(
            model_name='customerdesign',
            old_name='generated_model',
            new_name='model_url',
        ),
    ]
