# Generated by Django 5.1.7 on 2025-05-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_design_prompt_customerdesign_design_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdesign',
            name='model_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customerdesign',
            name='model_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
