# Generated by Django 5.1.7 on 2025-05-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_customerdesign_model_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdesign',
            name='model_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdesign',
            name='model_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
