# Generated by Django 5.1.7 on 2025-05-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_customerdesign_model_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdesign',
            name='height',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerdesign',
            name='thickness',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerdesign',
            name='width',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
