# Generated by Django 5.1.7 on 2025-05-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_customerdesign_height_customerdesign_thickness_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerdesign',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='customerdesign',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
