# Generated by Django 5.1.7 on 2025-05-12 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_customerdesign_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='customer_design',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': 'approved'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.customerdesign'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('product__isnull', False), ('customer_design__isnull', True)), models.Q(('product__isnull', True), ('customer_design__isnull', False)), _connector='OR'), name='cartitem_must_be_product_or_customer_design', violation_error_message='CartItem must be linked to either a Product or a Customer Design, but not both.'),
        ),
    ]
