# Generated by Django 5.1.7 on 2025-05-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_cartitem_customer_design_alter_cartitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdesign',
            name='is_added_to_cart',
            field=models.BooleanField(default=False),
        ),
    ]
