# Generated by Django 5.1.7 on 2025-05-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_customerdesign_is_added_to_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='php', max_length=10),
        ),
    ]
