# Generated by Django 5.1.7 on 2025-06-02 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_orderitem_customer_design_alter_orderitem_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
    ]
