# Generated by Django 5.1.7 on 2025-06-16 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymentMethod',
            field=models.CharField(choices=[('cash_on_delivery', 'Cash on Delivery'), ('stripe', 'Stripe'), ('gcash', 'GCash')], default='cash_on_delivery', max_length=50),
        ),
    ]
