# Generated by Django 5.1.7 on 2025-06-16 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_order_paymentmethod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paymentMethod',
            new_name='payment_method',
        ),
    ]
