# Generated by Django 5.1.7 on 2025-07-13 17:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_customeraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
