# Generated by Django 5.1.7 on 2025-07-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_customeraddress_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='latitude',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='longitude',
            field=models.CharField(blank=True, null=True),
        ),
    ]
