# Generated by Django 5.1.7 on 2025-07-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_customeraddress_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='barangay',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='city',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='postal_code',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='province',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='region',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='street',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
